name: Daily Mail Workflow

on:
  schedule:
    - cron: "0 3 * * *"   # रोज़ 8:30 AM IST
  workflow_dispatch:

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install msmtp
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp ca-certificates

      - name: Setup msmtp config
        run: |
          cat <<EOF > ~/.msmtprc
          defaults
          auth           on
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          account        gmail
          host           smtp.gmail.com
          port           587
          from           $GMAIL_USER
          user           $GMAIL_USER
          password       $GMAIL_PASS
          account default : gmail
          EOF
          chmod 600 ~/.msmtprc
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}

      - name: Run Shiva Daily Script
        run: ./shiva_daily.sh
