name: Daily Mail Test Workflow

on:
  schedule:
    - cron: "0 3 * * *"   # रोज़ सुबह 8:30 AM IST (3 AM UTC)
  workflow_dispatch:       # Manual run option (button मिलेगा)

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x shiva_daily.sh

      - name: Run shiva_daily.sh
        run: ./shiva_daily.sh

